import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of use',
  description:
    'Terms of use for the Trading Agents Lab marketing site and desktop application.',
  robots: { index: false, follow: true },
};

export default function Terms() {
  return (
    <article className="container-prose section">
      <span className="badge">legal · terms</span>
      <h1 className="mt-6 text-4xl">Terms of Use</h1>
      <p
        className="mt-3 text-xs text-[var(--color-text-muted)]"
        style={{ fontFamily: 'var(--font-mono)' }}
      >
        Last updated: 2026-05-16
      </p>

      <div className="docs-prose mt-10">
        <h2>1. Acceptance.</h2>
        <p>
          By accessing the website at <code>tradingagentslab.ai</code>{' '}
          (the &quot;Site&quot;) or by downloading, installing, or using
          the Trading Agents Lab desktop application (the
          &quot;Software&quot;), you agree to these Terms of Use (the
          &quot;Terms&quot;). If you do not agree, do not use the Site
          or the Software.
        </p>

        <h2>2. The Software is licensed under AGPL-3.0.</h2>
        <p>
          The Software is licensed under the GNU Affero General Public
          License v3.0. Your rights to use, modify, and distribute the
          Software are governed by that license; these Terms do not
          restrict those rights and, in the event of conflict, the
          AGPL-3.0 controls. Read the full text at{' '}
          <a
            href="https://www.gnu.org/licenses/agpl-3.0.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            gnu.org/licenses/agpl-3.0.html
          </a>
          .
        </p>

        <h2>3. Educational and research use only.</h2>
        <p>
          The Software is provided strictly for educational and research
          purposes. Output from the Software is not investment advice
          and must not be relied upon as the sole basis for any
          investment decision. See the{' '}
          <Link href="/legal/disclaimer/" className="prose-link">
            full Disclaimer
          </Link>{' '}
          for the controlling language.
        </p>

        <h2>4. You assume all risk.</h2>
        <p>
          Use of the Software is at your sole risk. The Software
          produces output generated by third-party large language
          models, which may be inaccurate, biased, or fabricated. Any
          decision you make on the basis of the Software&apos;s output
          is your responsibility alone, and any resulting losses are
          your responsibility alone.
        </p>

        <h2>5. No warranty.</h2>
        <p>
          The Site and the Software are provided &quot;AS IS&quot; and
          &quot;AS AVAILABLE&quot;, without warranty of any kind,
          express or implied. We disclaim all warranties, including
          merchantability, fitness for a particular purpose, accuracy,
          and non-infringement. We do not warrant that the Site or
          Software will be uninterrupted, timely, secure, or error-free,
          or that the output of the Software will be reliable or
          suitable for any purpose.
        </p>

        <h2>6. Limitation of liability.</h2>
        <p>
          To the maximum extent permitted by applicable law, in no event
          shall Trading Agents Lab, its authors, maintainers,
          contributors, or affiliated parties be liable for any
          indirect, incidental, special, consequential, or punitive
          damages, including but not limited to lost profits, lost
          revenue, lost data, or trading losses, arising out of or in
          connection with your use of the Site or the Software, even if
          advised of the possibility of such damages. The Software is
          provided to you free of charge; our maximum aggregate
          liability to you for any claim shall not exceed one U.S.
          dollar (USD $1.00).
        </p>

        <h2>7. Third-party providers.</h2>
        <p>
          The Software connects to third-party services that you
          configure (LLM providers, market-data providers, webhook
          receivers). Your relationship with each of those services is
          governed by their own terms and pricing. You are responsible
          for any charges you incur by configuring those providers with
          your own API keys.
        </p>

        <h2>8. Acceptable use.</h2>
        <p>
          You agree not to use the Site or Software (a) to violate any
          applicable law; (b) to attempt to attack, probe, or
          circumvent the security of any system; (c) to misrepresent
          the Software&apos;s output as personal investment advice from
          us to any third party; or (d) to facilitate market
          manipulation, insider trading, or any other fraudulent or
          deceptive practice.
        </p>

        <h2>9. Modifications.</h2>
        <p>
          We may update these Terms from time to time. The
          &quot;Last updated&quot; date above reflects the current
          version. Material changes will be announced via the project
          repository&apos;s release notes. Continued use of the Site or
          Software after a change constitutes acceptance of the updated
          Terms.
        </p>

        <h2>10. Governing law.</h2>
        <p>
          These Terms are governed by the laws of the State of Texas,
          United States, without regard to its conflict-of-laws
          provisions. You agree to the exclusive jurisdiction of the
          state and federal courts located in Travis County, Texas, for
          any dispute arising out of or relating to these Terms or your
          use of the Site or Software.
        </p>

        <h2>11. Contact.</h2>
        <p>
          Questions about these Terms: open an issue on{' '}
          <a
            href="https://github.com/RBJGlobal/TradingAgentsLab/issues"
            target="_blank"
            rel="noopener noreferrer"
          >
            our GitHub repository
          </a>
          .
        </p>

        <hr />

        <p className="text-sm text-[var(--color-text-muted)]">
          <em>
            These Terms are a plain-language draft pending review by
            licensed counsel. They will be reviewed and updated before
            any public distribution build of the Software is signed and
            shipped.
          </em>
        </p>
      </div>
    </article>
  );
}
